name: Deploy WP-Select-P-Category to WP.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Plugin Deploy
        uses: mobeenabdullah/WP-Select-Primary-Category@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wp-select-primary-category